# Generated by Django 5.0.6 on 2024-07-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
